### ISSUE TITLE
Fix rust format

### ISSUE THREAD

**Issue by mrseanryan** [mrseanryan/in_definite#9]
Currently rust formatting is disabled in rustfmt.toml, since different editors produce different formatting.

This makes it tricky for contributors.

To resolve this issue, we can configure rust formatting to work in common editors.

- Visual Code
- Sublime
- Other?

**Comment by dmit** [comment]
As far as I know, most (all?) editors call rustfmt when formatting Rust code, so the result should be consistent between different IDEs and editor plugins.

The reason I disabled rustfmt in my PR is because it didn't look like this project was using it. Setting `disable_all_formatting = true` in rustfmt.toml helps avoid situations where a contributor makes a small functional change, but their editor auto-reformats everything.

Here's what the code would look like when formatted with rustfmt's default config btw: dmit@05cd14906aebaa9f3931c660ffdb47741a40c2c2. It's mostly whitespace changes and a couple missing commas/semicolons.

If the above style changes look ok to you, I can submit a PR for this as well, @mrseanryan. Or we can tweak the [style rules](https://rust-lang.github.io/rustfmt/) first.

**Comment by mrseanryan** [comment]
Hi @dmit I see - probably something wrong on my side.

I will look at that commit and get back to you...

**Comment by mrseanryan** [comment]
@dmit  thanks for explaining - I did not really know about rustfmt before.

Have added it, with scripts.  Seems to format just as in your commit.

cheers,
Sean
